/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.*;
import entity.Rental;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.*;

/**
 *
 * @author habibi dan riska
 */
public class RentalTransaksi extends javax.swing.JFrame {

    SintakRental dao = new SintakRental();
    Rental pj;
    String tglHarus;
    String tglKbl;
    int total = 0;

    /**
     * Creates new form RentalTransaksi
     */
    public RentalTransaksi() {
        initComponents();
        Tanggal();
        setTitle("FORM TRANSAKSI");
        setLocation(200, 20);
        txtUserlog.setText(Login.getNamaUser());
        txtMember.requestFocus();
        //membuat data di tabel transaksi
        List<Rental> list = new ArrayList<Rental>();
        TableModel tableModel = new TabelTransaksi(list);
        tabelTrans.setModel(tableModel);
        DisabledAll();

    }

    //method untuk mendapatkan data tanggal yg dimodifikasi
    private void Tanggal() {
        Calendar tanggal = Calendar.getInstance();
        Date sekarang = tanggal.getTime();
        SimpleDateFormat sdformat = new SimpleDateFormat("dd-MM-yyyy");
        sdformat.setLenient(false);
        String tgl;
        try {
            tgl = sdformat.format(sekarang);
        } catch (IllegalArgumentException ex) {
            tgl = "Error : " + ex.getMessage();
        }
        txtDate.setText(tgl);
    }

    //method untuk refresh form dan membuat transaksi baru
    private void Refresh() {
        txtNotrans.setText("");
        txtMember.setText("");
        txtNama.setText("");
        txtKodedvd.setText("");
        txtJudul.setText("");
        txtJmlPin.setText("");
        txtTglHarus.setDate(null);
        txtTglKbl.setDate(null);
        txtJmlKbl.setText("");
        txtDenda.setText("");
        txtTotal.setText("");
        txtBayar.setText("");
        txtKbl.setText("");
        txtStok.setText("");
        txtSewa.setText("");
        txtDetail.setText("");
        txtMember.setEditable(true);
        btnCreate.setEnabled(true);
        btnSearch.setEnabled(true);
        List<Rental> list = new ArrayList<Rental>();
        TableModel tableModel = new TabelTransaksi(list);
        tabelTrans.setModel(tableModel);
        DisabledAll();
        txtMember.requestFocus();
    }

    private void DisabledAll() {
        txtDetail.setEditable(false);
        txtNotrans.setEditable(false);
        txtKodedvd.setEditable(false);
        txtJudul.setEditable(false);
        txtJmlPin.setEditable(false);
        txtStok.setEditable(false);
        txtSewa.setEditable(false);
        txtTglHarus.setEnabled(false);
        txtTglKbl.setEnabled(false);
        txtJmlKbl.setEditable(false);
        txtDenda.setEditable(false);
        txtTotal.setEditable(false);
        txtBayar.setEditable(false);
        txtKbl.setEditable(false);
        btnSearch2.setEnabled(false);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnProses.setEnabled(false);
        btnCancel.setEnabled(false);
        btnGratis.setEnabled(false);
    }

    //method untuk mendapatkan data tanggal
    public String TglSkrg() {
        Date skrg = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return format.format(skrg);
    }

    //method untuk mendapatkan data tahun
    public String ThnSkrg() {
        Date skrg = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy");
        return format.format(skrg);
    }

    //method untuk mendapat nomor detail
    public void Nodetail() {
        dao.getNodetail(pj);
        int nmr = pj.getNodetail() + 1;
        txtDetail.setText(String.valueOf(nmr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        String lookAndFeel = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try{
            javax.swing.UIManager.setLookAndFeel(lookAndFeel);
        }catch(Exception e){}
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNotrans = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUserlog = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKodedvd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtJmlPin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTglHarus = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTrans = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        txtKbl = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTglKbl = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtJmlKbl = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtSewa = new javax.swing.JTextField();
        txtDetail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTes1 = new javax.swing.JLabel();
        txtTes2 = new javax.swing.JLabel();
        txtTes3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnGratis = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Date");

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setText("Kode Member");

        txtMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Member");

        jLabel5.setText("No. Transaksi");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Welcome,");

        txtUserlog.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        txtUserlog.setForeground(new java.awt.Color(51, 51, 255));

        jLabel6.setText("Kode DVD");

        txtKodedvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodedvdActionPerformed(evt);
            }
        });

        jLabel7.setText("Judul");

        jLabel8.setText("Jml Dipinjam");

        jLabel11.setText("Tgl Harus Kembali");

        txtTglHarus.setDateFormatString("d MMM yyyy");
        txtTglHarus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTglHarusPropertyChange(evt);
            }
        });

        tabelTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelTrans);

        jLabel2.setText("Total");

        jLabel12.setText("Bayar");

        jLabel13.setText("Kembali");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        jLabel14.setText("Denda");

        jLabel15.setText("Tgl Kembali");

        txtTglKbl.setDateFormatString("d MMM yyyy");
        txtTglKbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTglKblPropertyChange(evt);
            }
        });

        jLabel16.setText("Jml DVD Kembali");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("NB : Setiap memasukkan kode member dan kode dvd, harap untuk menekan enter");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("DAFTAR PINJAMAN");

        jLabel19.setText("Stok");

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        btnCreate.setText("Create Trans");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel20.setText("Harga Sewa");

        jLabel21.setText("No. Detail Trans");

        btnCancel.setText("Cancel Trans");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnGratis.setText("Gratis");
        btnGratis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGratisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUserlog, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(208, 208, 208)
                                    .addComponent(jLabel1)
                                    .addGap(12, 12, 12))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtJmlPin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(170, 170, 170))
                                            .addComponent(txtJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNotrans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtTglHarus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                                    .addComponent(txtKodedvd))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnSearch2)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGratis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSearch))
                                    .addComponent(jLabel4))
                                .addGap(224, 224, 224))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreate))
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKbl, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTes1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtTes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(677, 677, 677))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnProses))
                                    .addComponent(txtTglKbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJmlKbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUserlog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNotrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodedvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnSearch2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnDelete)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTglHarus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSave)
                                .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(btnGratis))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJmlKbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(txtTes1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTes2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addComponent(txtTglKbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtTes3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(37, 37, 37)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Form Master");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Form Member");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Form Petugas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Form Pencarian");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Edit");

        jMenuItem7.setText("Edit Akun");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("System");

        jMenuItem5.setText("Form Transaksi");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTglHarusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTglHarusPropertyChange
        if (txtTglHarus.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
            tglHarus = Format.format(txtTglHarus.getDate());
        }
    }//GEN-LAST:event_txtTglHarusPropertyChange

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberActionPerformed
        try {
            dao.connect();
            pj = new Rental();
            dao.getValueMem(txtMember.getText(), pj);

            if (pj.getRow() == 1) {
                txtNama.setText(pj.getNamamem());

                //mendapatkan nilai dari yang dicari
                List<Rental> list = new ArrayList<Rental>();
                list = new ArrayList<Rental>();
                list = dao.listPinjam(txtMember.getText());
                //menampilkan yang dicari
                TableModel tableModel = new TabelTransaksi(list);
                tabelTrans.setModel(tableModel);

                txtMember.setEditable(false);
                txtNama.setEditable(false);
                btnSearch.setEnabled(false);
                btnCreate.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Kode Member tidak ada!!", "Warning", JOptionPane.ERROR_MESSAGE);
            }

            dao.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMemberActionPerformed

    private void txtKodedvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodedvdActionPerformed
        try {
            dao.connect();
            pj = new Rental();
            dao.getValueDVD(txtKodedvd.getText(), pj);

            if (pj.getRow() == 1) {
                txtJudul.setText(pj.getJudul());
                txtStok.setText(String.valueOf(pj.getStok()));
                txtSewa.setText(String.valueOf(pj.getSewa()));
                txtJudul.setEditable(false);
                txtStok.setEditable(false);
                txtSewa.setEditable(false);
                txtJmlPin.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Kode DVD tidak ada!!", "Warning", JOptionPane.ERROR_MESSAGE);
            }

            dao.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtKodedvdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtMember.getText().equals("") && txtKodedvd.getText().equals("") && txtJmlPin.getText().equals("") && tglHarus.equals(null)) {
            JOptionPane.showMessageDialog(null, "Text Field harus diisi semua !!", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                if (Integer.parseInt(txtStok.getText()) != 0) {
                    if (Integer.parseInt(txtJmlPin.getText()) <= Integer.parseInt(txtStok.getText())) {
                        pj = new Rental();
                        //generate kode index
                        int jum = String.valueOf(txtDetail.getText()).length();
                        int jumlah = 4 - jum;
                        String nol = "";
                        for (int i = 1; i < jumlah; i++) {
                            nol = nol + "0";
                        }
                        pj.setIndex(txtNotrans.getText() + nol + txtDetail.getText());

                        //mendapatkan inputan di textfield
                        pj.setKodedvd(txtKodedvd.getText().toUpperCase());
                        pj.setNotrans(txtNotrans.getText());
                        pj.setJmldvd(Integer.parseInt(txtJmlPin.getText()));
                        pj.setNodetail(Integer.parseInt(txtDetail.getText()));
                        pj.setSewa(Integer.parseInt(txtSewa.getText()) * Integer.parseInt(txtJmlPin.getText()));
                        pj.setStok(Integer.parseInt(txtStok.getText()));
                        pj.setTglharus(tglHarus);

                        dao.connect();
                        dao.insertdetail(pj);
                        List<Rental> list = new ArrayList<Rental>();
                        //membaca datanya ke list
                        list = dao.listPinjam(txtMember.getText());
                        //menampilkan data ke tabel
                        TableModel tabelModel = new TabelTransaksi(list);
                        tabelTrans.setModel(tabelModel);

                        //menampilkan total bayar
                        total = total + pj.getSewa();
                        txtTotal.setText(String.valueOf(total));
                        Nodetail();

                        txtKodedvd.setText("");
                        txtJudul.setText("");
                        txtStok.setText("");
                        txtSewa.setText("");
                        txtJmlPin.setText("");
                        btnDelete.setEnabled(true);
                        txtTglHarus.setDate(null);
                        txtKodedvd.requestFocus();

                        dao.disconnect();
                    } else {
                        JOptionPane.showMessageDialog(null, "Jumlah yang dipinjam melebihi stok", "Warning", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Stok DVD kosong", "Warning", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "no tidak boleh sama ");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            pj = new Rental();
            dao.connect();
            //mendapatkan nomor trans
            dao.setNotrans(ThnSkrg());
            int digit = Integer.parseInt(dao.getNotrans()) + 1;
            txtNotrans.setText(String.valueOf(digit));

            //create transaksi baru dan insert ke database
            pj.setNotrans(txtNotrans.getText());
            pj.setKodemem(txtMember.getText());
            pj.setKodepeg(txtUserlog.getText());
            pj.setTgltrans(txtDate.getText());
            dao.inserttrans(pj);
            Nodetail();

            //enabled text field
            txtKodedvd.setEditable(true);
            txtJmlPin.setEditable(true);
            txtTglHarus.setEnabled(true);
            txtBayar.setEditable(true);
            txtKbl.setEditable(true);
            btnSearch2.setEnabled(true);
            btnSave.setEnabled(true);
            btnCancel.setEnabled(true);
            btnGratis.setEnabled(true);

            txtKodedvd.requestFocus();
            dao.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void tabelTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransMouseClicked
        int selected = tabelTrans.getSelectedRow();
        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Klik row tabel");
        } else {
            //mendapatkan value nomor transaksi di tabel detail trans dan memasukkannya ke text field
            String index = tabelTrans.getValueAt(selected, 0).toString();
            String trans = index.substring(0, 10);
            String detail = index.substring(10);
            int det = Integer.parseInt(detail);
            txtNotrans.setText(trans);
            txtDetail.setText(String.valueOf(det));

            txtKodedvd.setText((String) tabelTrans.getValueAt(selected, 1));
            txtJmlPin.setText((String) tabelTrans.getValueAt(selected, 2).toString());

            //set tanggal harus kembali di text field
            String dateValue = String.valueOf(tabelTrans.getValueAt(selected, 4));
            Date date = new Date();
            try {
                date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            } catch (ParseException ex) {
                Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtTglHarus.setDate(date);

            //mendapatkan value untuk kode dvd
            try {
                dao.connect();
                pj = new Rental();
                dao.getValueDVD(txtKodedvd.getText(), pj);
                if (pj.getRow() == 1) {
                    txtJudul.setText(pj.getJudul());
                    txtStok.setText(String.valueOf(pj.getStok()));
                    txtSewa.setText(String.valueOf(pj.getSewa()));
                    txtJudul.setEditable(false);
                    txtStok.setEditable(false);
                    txtSewa.setEditable(false);
                    txtJmlKbl.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtTglKbl.setEnabled(true);
            txtJmlKbl.setEditable(true);
            txtKbl.setEditable(true);
            txtBayar.setEditable(true);
            btnProses.setEnabled(true);
            btnCreate.setEnabled(false);

        }
    }//GEN-LAST:event_tabelTransMouseClicked

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        try {
            pj = new Rental();
            dao.connect();

            //validasi jumlah dvd yang dikembalikan
            if (Integer.parseInt(txtJmlKbl.getText()) <= Integer.parseInt(txtJmlPin.getText())) {
                //memasukkan tanggal kembali ke database
                pj.setKodepeg(txtUserlog.getText());
                pj.setKodedvd(txtKodedvd.getText());
                pj.setJmlkbl(Integer.parseInt(txtJmlKbl.getText()));
                pj.setJmldvd(Integer.parseInt(txtJmlPin.getText()));
                pj.setTglkbl(tglKbl);
                pj.setNodetail(Integer.parseInt(txtDetail.getText()));
                pj.setNotrans(txtNotrans.getText());

                //menyimpan variabel denda
                pj.setDenda(Integer.parseInt(txtDenda.getText()));

                //memasukkan data ke tabel detail transaksi
                dao.transKembali(pj);
                total = total + Integer.parseInt(txtDenda.getText());
                txtTotal.setText(String.valueOf(total));

                //set status untuk peminjaman DVD (Borrowed atau Returned)
                dao.cekJml(pj);
                if (pj.getJmlkbl() == 0) {
                    dao.rubahStat(pj);
                }

                List<Rental> list = new ArrayList<Rental>();
                //membaca datanya ke list
                list = dao.listPinjam(txtMember.getText());
                //menampilkan data ke tabel
                TableModel tabelModel = new TabelTransaksi(list);
                tabelTrans.setModel(tabelModel);

                txtKodedvd.setText("");
                txtNotrans.setText("");
                txtDetail.setText("");
                txtDenda.setText("");
                txtTglHarus.setDate(null);
                txtTglKbl.setDate(null);
                txtJudul.setText("");
                txtStok.setText("");
                txtJmlPin.setText("");
                txtJmlKbl.setText("");
                txtSewa.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "Jumlah DVD yang dikembalikan tidak cocok", "Warning", JOptionPane.ERROR_MESSAGE);
            }
            dao.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtTglKblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTglKblPropertyChange
        if (txtTglKbl.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
            tglKbl = Format.format(txtTglKbl.getDate());

            try {
                dao.connect();
                pj = new Rental();
                int tot = 0;

                pj.setTglkbl(tglKbl);
                pj.setTglharus(tglHarus);

                //menghitung denda
                dao.cekDenda(Integer.parseInt(txtDetail.getText()), pj);
                dao.getValueDVD(txtKodedvd.getText(), pj);
                dao.valueGeneral(pj.getStatus(), pj);

                tot = tot + (pj.getLama() / pj.getLamapin() * pj.getDendapin() * Integer.parseInt(txtJmlKbl.getText()));
                tot = tot + (pj.getLama() % pj.getLamapin() * pj.getDendapin() * Integer.parseInt(txtJmlKbl.getText()));
                txtDenda.setText(String.valueOf(tot));

                dao.disconnect();
            } catch (SQLException ex) {
                Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtTglKblPropertyChange

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        int tot = Integer.parseInt(txtTotal.getText());
        int bayar = Integer.parseInt(txtBayar.getText());
        int kbl = bayar - tot;
        txtKbl.setText(String.valueOf(kbl));
    }//GEN-LAST:event_txtBayarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        PickMember pick = new PickMember(new javax.swing.JFrame(), true);
        pick.setVisible(true);
        if (pick.isSucceeded()) {
            txtMember.setText(pick.getKodeMember());
            txtMember.requestFocus();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        PickDVD pick = new PickDVD(new javax.swing.JFrame(), true);
        pick.setVisible(true);
        if (pick.isSucceeded()) {
            txtKodedvd.setText(pick.getKodeDVD());
            txtKodedvd.requestFocus();
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int konf = JOptionPane.showConfirmDialog(null, "Anda yakin mau logout?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        switch (konf) {
            case JOptionPane.YES_OPTION:
                try {
                    dao.connect();
                    dao.userLogout(txtUserlog.getText(), TglSkrg());
                    new Login().setVisible(true);
                    this.setVisible(false);
                    dao.disconnect();
                } catch (SQLException ex) {
                    Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
                }

            default:
            //do nothing
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        pj = new Rental();
        try {
            dao.connect();
            dao.delTrans(txtNotrans.getText());
            //reresh field
            Refresh();
            dao.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            pj = new Rental();
            pj.setSewa(Integer.parseInt(txtSewa.getText()) * Integer.parseInt(txtJmlPin.getText()));
            pj.setNotrans(txtNotrans.getText());
            pj.setStok(Integer.parseInt(txtStok.getText()));
            pj.setJmldvd(Integer.parseInt(txtJmlPin.getText()));
            pj.setKodedvd(txtKodedvd.getText());

            int noBaris = tabelTrans.getSelectedRow();
            //jika baris tidak di klik
            if (noBaris < 0) {
                return;
            }

            if (JOptionPane.showConfirmDialog(this, "Yakin menghapus data", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.CANCEL_OPTION) {
                return;
            }
            //mendapatkan nilai no dari tabel yang di klik
            Object index = tabelTrans.getValueAt(noBaris, 0);
            dao.connect();
            dao.deletedetail(String.valueOf(index), pj);
            List<Rental> list = new ArrayList<Rental>();
            list = dao.listPinjam(txtMember.getText());
            //menampilkan data ke tabel
            TableModel tabelModel = new TabelTransaksi(list);
            tabelTrans.setModel(tabelModel);

            //menampilkan total bayar
            total = total - pj.getSewa();
            txtTotal.setText(String.valueOf(total));
            Nodetail();

            txtKodedvd.setText("");
            txtJudul.setText("");
            txtStok.setText("");
            txtSewa.setText("");
            txtJmlPin.setText("");
            txtKodedvd.setEditable(true);
            txtJmlPin.setEditable(true);
            btnSearch2.setEnabled(true);
            txtTglHarus.setEnabled(true);
            btnGratis.setEnabled(true);
            txtTglHarus.setDate(null);
            txtKodedvd.requestFocus();

            dao.disconnect();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan : " + ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnGratisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGratisActionPerformed
        if (txtMember.getText().equals("") && txtKodedvd.getText().equals("") && txtJmlPin.getText().equals("") && tglHarus.equals(null)) {
            JOptionPane.showMessageDialog(null, "Text Field harus diisi semua !!", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                if (Integer.parseInt(txtStok.getText()) != 0) {
                    if (Integer.parseInt(txtJmlPin.getText()) <= Integer.parseInt(txtStok.getText())) {
                        pj = new Rental();
                        //generate kode index
                        int jum = String.valueOf(txtDetail.getText()).length();
                        int jumlah = 4 - jum;
                        String nol = "";
                        for (int i = 1; i < jumlah; i++) {
                            nol = nol + "0";
                        }
                        pj.setIndex(txtNotrans.getText() + nol + txtDetail.getText());

                        //mendapatkan inputan di textfield
                        pj.setKodedvd(txtKodedvd.getText().toUpperCase());
                        pj.setNotrans(txtNotrans.getText());
                        pj.setJmldvd(Integer.parseInt(txtJmlPin.getText()));
                        pj.setNodetail(Integer.parseInt(txtDetail.getText()));
                        pj.setSewa(Integer.parseInt(txtSewa.getText()) * Integer.parseInt(txtJmlPin.getText()));
                        pj.setStok(Integer.parseInt(txtStok.getText()));
                        pj.setTglharus(tglHarus);

                        dao.connect();
                        dao.insertgratis(pj);
                        List<Rental> list = new ArrayList<Rental>();
                        //membaca datanya ke list
                        list = dao.listPinjam(txtMember.getText());
                        //menampilkan data ke tabel
                        TableModel tabelModel = new TabelTransaksi(list);
                        tabelTrans.setModel(tabelModel);

                        Nodetail();

                        txtKodedvd.setText("");
                        txtJudul.setText("");
                        txtStok.setText("");
                        txtSewa.setText("");
                        txtJmlPin.setText("");
                        btnDelete.setEnabled(true);
                        txtTglHarus.setDate(null);
                        txtKodedvd.requestFocus();

                        dao.disconnect();
                    } else {
                        JOptionPane.showMessageDialog(null, "Jumlah yang dipinjam melebihi stok", "Warning", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Stok DVD kosong", "Warning", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "no tidak boleh sama ");
            }
        }
    }//GEN-LAST:event_btnGratisActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new RentalView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new RentalMember().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new RentalPencarian().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new EditAkun().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new RentalTransaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        int konf = JOptionPane.showConfirmDialog(null, "Anda yakin mau logout?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        switch (konf) {
            case JOptionPane.YES_OPTION:
                try {
                    dao.connect();
                    dao.userLogout(txtUserlog.getText(), TglSkrg());
                    new Login().setVisible(true);
                    this.setVisible(false);
                    dao.disconnect();
                } catch (SQLException ex) {
                    Logger.getLogger(RentalTransaksi.class.getName()).log(Level.SEVERE, null, ex);
                }

            default:
            //do nothing
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RentalTransaksi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGratis;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelTrans;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtDetail;
    private javax.swing.JTextField txtJmlKbl;
    private javax.swing.JTextField txtJmlPin;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKbl;
    private javax.swing.JTextField txtKodedvd;
    private javax.swing.JTextField txtMember;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNotrans;
    private javax.swing.JTextField txtSewa;
    private javax.swing.JTextField txtStok;
    private javax.swing.JLabel txtTes1;
    private javax.swing.JLabel txtTes2;
    private javax.swing.JLabel txtTes3;
    private com.toedter.calendar.JDateChooser txtTglHarus;
    private com.toedter.calendar.JDateChooser txtTglKbl;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtUserlog;
    // End of variables declaration//GEN-END:variables
}
